name: echo

on: 
  workflow_call:
    inputs:
      message:
        type: string
        description: Something to print out
        default: "JFokus 2023"
        required: false


jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${{ inputs.message }}