name: CI

on:
  pull_request:
    branches:
      - main

concurrency: 
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        command: [lint, "test:ci", e2e] 
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup NodeJS 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: 'yarn'

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            /home/runner/.cache/Cypress
            **/node_modules
          key: our-cache-yarn-${{ hashFiles('**/yearn.lock.json') }}

      - name: Install dependencies
        run: yarn install

      - name: ${{ matrix.command }}
        run: yarn ${{ matrix.command }}
  echo:
    uses: middlesister/jfokus2023-github-actions/.github/workflows/_echo.yml@reusable
    with:
      message: "another message"
  
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./tools/custom-actions/e2e/
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
